version: 2
jobs:
  test:
    docker:
      - image: opensourcecobol/opensource-cobol
    steps:
      - checkout
      - run: cobc -m -o ZINKO-CNV.so ZINKO-CNV.cbl
      - run: cobc -m -o MENSEKI-CNV.so MENSEKI-CNV.cbl
      - run: cobc -m -o ZINKOMITSUDO.so ZINKOMITSUDO.cbl
      - run: cobcrun ZINKO-CNV
      - run: cobcrun MENSEKI-CNV
      - run: cobcrun ZINKOMITSUDO
      - run: diff TOP5.txt TOP5_RESULT.txt
      - run: mkdir /tmp/test-results
      - run: cp mitsudo.csv /tmp/test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/test-results
      #    destination: prefix
workflows:
  version: 2
  test:
    jobs:
      - test
