version: 2
jobs:
  test:
    docker:
      - image: opensourcecobol/opensource-cobol
    steps:
      - checkout
      - run: cobc -m -o HELLO.so HELLO.cbl
      - run: cobcrun HELLO
      - run: cobc -m -o HELLO2.so HELLO2.cbl
      - run: cobcrun HELLO2
      - run: cat SEQ001
      - run: mkdir /tmp/test-results
      - run: cp HELLO2.so SEQ001 /tmp/test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/test-results
      #    destination: prefix
workflows:
  version: 2
  test:
    jobs:
      - test
